# define here how the build will be named
name: $(Build.SourceBranchName)_$(Build.Reason)_.$(Build.BuildId)$(Rev:.r) 

# Run on changes to dev, test and prod
trigger:
  branches:
    include: 
      - dev
 
variables:
  - name: azureSqlServerName 
    value: formaciosembismart.database.windows.net
  - name: azureSubscription
    value:  sepr-joanteixi-d1
  - name:  databaseName
    value: formaciosem-basic
 
stages:
- template: azure-pipelines-ci.yml
  parameters:
    dropDacpacName: dropDacpacDev
    solutionDirectory: './'
- template: azure-pipelines-cd.yml  
  parameters:
    dropDacpacName: dropDacpacDev
    azureSubscription: $(azureSubscription)
    solutionDirectory: './'
    projectDB: 'shopOnlineDB'
    serverName: $(azureSqlServerName)
    databaseName: $(databaseName)
    blockDataLossOnDeployment: 'False'
